sudo: required
language: node_js
node_js:
  - "8"
cache:
  yarn: true

before_script:
  - rm -rf dist
script:
  - BASENAME= yarn build

deploy:
  local-dir: dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
